name: jasafix_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^8.0.2
  flutter_svg: ^2.0.9

  # Routing
  go_router: ^17.2.1
  
  # State management
  provider: ^6.1.1
  
  # HTTP client
  dio: ^5.4.0
  
  # WebSocket (Laravel Reverb / real-time features)
  socket_io_client: ^3.1.4
  
  # Local storage
  shared_preferences: ^2.2.2
  
  # Formatting (dates, currency, locale)
  intl: ^0.20.2
  
  # Value comparison (useful for state & models)
  equatable: ^2.0.5
  
  # JSON model annotations (used with build_runner)
  json_annotation: ^4.8.1
  
  # Image picker (camera/gallery)
  image_picker: ^1.0.5
  
  # Network image caching
  cached_network_image: ^3.3.1
  
  # Loading placeholders
  shimmer: ^3.0.0
  
  # Star rating UI
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  
  # Code generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - lib/data/mock_data/